export const SERVICES = [
  {
    title: "Aluguer e Venda de Veículos",
    description:
      "Seja por alguns dias ou para sempre, a V&H Investimentos oferece a solução perfeita para você. Com uma ampla frota de veículos de diversos modelos e categorias, garantimos que você encontrará o carro ideal para qualquer ocasião – sempre com conforto e estilo.",
    icon: "/assets/servicos/carro.svg",
  },
  {
    title: "Venda e Encomenda de peças",
    description:
      "Trabalhamos com peças automotivas originais importadas dos Estados Unidos, garantindo máxima qualidade e durabilidade para o seu veículo. Encontre ou encomende peças para todas as marcas e modelos, com garantia de procedência.",
    icon: "/assets/servicos/carro.svg",
  },
  {
    title: "Aluguer Personalizado",
    description:
      "Poupe tempo e preocupações. Vamos onde estiver, entregamos e recolhemos o veículo no local da sua preferência, de forma rápida e segura. Seja para aluguer ou compra, garantimos uma experiência sem complicações.",
    icon: "/assets/servicos/carro.svg",
  },
];

export const FAQs = [
  {
    title: "O que é preciso para alugar um veículo?",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut et massa mi. Aliquam in hendrerit urna. Pellentesque sit amet sapien fringilla, mattis ligula consectetur, ultrices mauris. Maecenas vitae mattis tellus.",
  },
  {
    title: "Preciso do meu próprio seguro?",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut et massa mi. Aliquam in hendrerit urna. Pellentesque sit amet sapien fringilla, mattis ligula consectetur, ultrices mauris. Maecenas vitae mattis tellus.",
  },
  {
    title: "Outras pessoas podem dirigir o veículo que eu aluguei?",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut et massa mi. Aliquam in hendrerit urna. Pellentesque sit amet sapien fringilla, mattis ligula consectetur, ultrices mauris. Maecenas vitae mattis tellus.",
  },
  {
    title: "Como funciona a política de cancelamento?",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut et massa mi. Aliquam in hendrerit urna. Pellentesque sit amet sapien fringilla, mattis ligula consectetur, ultrices mauris. Maecenas vitae mattis tellus.",
  },
  {
    title: "O que acontece se eu tiver um acidente?",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut et massa mi. Aliquam in hendrerit urna. Pellentesque sit amet sapien fringilla, mattis ligula consectetur, ultrices mauris. Maecenas vitae mattis tellus.",
  },
];

export const PRE_HEADER_HEIGHT = "50px";
export const HEADER_HEIGHT = "90px";

export const CARS = [
  {
    id: 1,
    name: "CHEVROLET",
    model: "TRAX LS",
    year: 2019,
    seats: 5,
    motor: "Motor Cilindrada 1364 C.C/Cm3, 4 Cilindros",
    fuel: "gasoline",
    transmission: "automatic",
    availableToRent: false,
    availableToSell: true,
    priceToRent: "",
    priceToSell: "1.600.000 CVE",
    image: "/src/assets/cars/chevrolet_trax_2019_dark_grey.png",
  },
  {
    id: 2,
    name: "JEEP",
    model: "RENAGADE SPORT 4X4",
    year: 2019,
    seats: 5,
    motor: "2360 C.C/Cm3, 4 Cilindros",
    fuel: "gasoline",
    transmission: "automatic",
    availableToRent: false,
    availableToSell: true,
    priceToRent: "",
    priceToSell: "2.100.000 CVE",
    image: "/src/assets/cars/jeep_renegade_sport_2019_black.png",
  },
  {
    id: 3,
    name: "FORD",
    model: "FUSION SE",
    year: 2018,
    seats: 5,
    motor: "Motor Cilindrada 1499 C.C/Cm3, 4 Cilindros",
    fuel: "gasoline",
    transmission: "automatic",
    availableToRent: false,
    availableToSell: true,
    priceToRent: "",
    priceToSell: "1.700.000 CVE",
    image: "/src/assets/cars/ford_fusion_se_2018_light_grey.png",
  },
  {
    id: 4,
    name: "CHEVROLET",
    model: "TRAX LT",
    year: 2020,
    seats: 5,
    motor: "Motor Cilindrada 1364 C.C/Cm3, 4 Cilindros",
    fuel: "gasoline",
    transmission: "automatic",
    availableToRent: false,
    availableToSell: true,
    priceToRent: "",
    priceToSell: "1.700.000 CVE",
    image: "/src/assets/cars/chevrolet_trax_ls_2020_white.png",
  },
  {
    id: 5,
    name: "JEEP",
    model: "COMPASS LATITUDE",
    year: 2021,
    seats: 5,
    motor: "Motor 2360 c.c/ cm3, 4 Cilindros",
    fuel: "gasoline",
    transmission: "automatic",
    availableToRent: false,
    availableToSell: true,
    priceToRent: "",
    priceToSell: "2.100.000 CVE",
    image: "/src/assets/cars/jeep_compass_latitude_2021_black.png",
  },
  {
    id: 6,
    name: "SURABU",
    model: "ASCENT",
    year: 2020,
    seats: 8,
    motor: "Motor 2360 c.c/ cm3, 4 Cilindros",
    fuel: "gasoline",
    transmission: "automatic",
    availableToRent: false,
    availableToSell: true,
    priceToRent: "",
    priceToSell: "2.700.000 CVE",
    image: "/src/assets/cars/subaru_ascent_2020_white.jpg",
  },
  {
    id: 7,
    name: "CHEVROLET",
    model: "TRAX LT AWD",
    year: 2019,
    seats: 5,
    motor: "Motor Cilindrada 1364 C.C/Cm3, 4 Cilindros",
    fuel: "gasoline",
    transmission: "automatic",
    availableToRent: false,
    availableToSell: true,
    priceToRent: "",
    priceToSell: "1.700.000 CVE",
    image: "/src/assets/cars/chevrolet_trax_2019_dark_grey.png",
  },
  {
    id: 8,
    name: "FIAT",
    model: "STRADA",
    year: 2023,
    seats: 5,
    motor: "Motor 1368 c.c/cm3, 4 Cilindros",
    fuel: "gasoline",
    transmission: "manual",
    availableToRent: true,
    availableToSell: false,
    priceToRent: "€60",
    priceToSell: "",
    securityDeposit: "€200",
    image: "/src/assets/cars/fiat_strada_endurance_2023_grey.png",
  },
  {
    id: 9,
    name: "FIAT",
    model: "STRADA",
    year: 2023,
    seats: 5,
    motor: "Motor 1368 c.c/cm3, 4 Cilindros",
    fuel: "gasoline",
    transmission: "manual",
    availableToRent: true,
    availableToSell: false,
    priceToRent: "€60",
    priceToSell: "",
    securityDeposit: "€200",
    image: "/src/assets/cars/fiat_strada_endurance_2023_grey.png",
  },
  {
    id: 10,
    name: "TOYOTA",
    model: "STARLET",
    year: 2024,
    seats: 5,
    motor: "Motor 1452 c.c/cm3, 4 Cilindros",
    fuel: "gasoline",
    transmission: "manual",
    availableToRent: true,
    availableToSell: false,
    priceToRent: "€44",
    priceToSell: "",
    securityDeposit: "€200",
    image: "/src/assets/cars/toyota_starlet_2024_blue.png",
  },
  {
    id: 11,
    name: "TOYOTA",
    model: "STARLET",
    year: 2024,
    seats: 5,
    motor: "Motor 1452 c.c/cm3, 4 Cilindros",
    fuel: "gasoline",
    transmission: "manual",
    availableToRent: true,
    availableToSell: false,
    priceToRent: "€44",
    priceToSell: "",
    securityDeposit: "€200",
    image: "/src/assets/cars/toyota_starlet_2024_brown.png",
  },
  {
    id: 12,
    name: "TOYOTA",
    model: "STARLET",
    year: 2024,
    seats: 5,
    motor: "Motor 1452 c.c/cm3, 4 Cilindros",
    fuel: "gasoline",
    transmission: "manual",
    availableToRent: true,
    availableToSell: false,
    priceToRent: "€44",
    priceToSell: "",
    securityDeposit: "€200",
    image: "/src/assets/cars/toyota_starlet_2024_light_grey.png",
  },
  {
    id: 13,
    name: "TOYOTA",
    model: "STARLET",
    year: 2024,
    seats: 5,
    motor: "Motor 1452 c.c/cm3, 4 Cilindros",
    fuel: "gasoline",
    transmission: "manual",
    availableToRent: true,
    availableToSell: false,
    priceToRent: "€44",
    priceToSell: "",
    securityDeposit: "€200",
    image: "/src/assets/cars/toyota_starlet_2024_light_grey.png",
  },
];

export const scrollToView = (item: string) => {
  const elementToScrollTo = document.getElementById(item);
  if (elementToScrollTo) {
    elementToScrollTo.scrollIntoView({ behavior: "smooth" });
  }
};
